import { type NextPage } from "next";
import Head from "next/head";
import {api} from "~/utils/api"


const ProfilePage: NextPage = () => {

  const {data,isLoading} = api.profile.getUserByUsername.useQuery({
    username: "yo150"
  })

  if(isLoading) return <h3>- Loading... -</h3>

  if(!data) return <h3>404</h3>

  console.log(data)

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
    
      <h2> {data.username}</h2>


      </main>
    </>
  );
};

export default ProfilePage;
